service: express-lambda-test

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 256
  timeout: 20
  stage: ${opt:stage, 'dev'} # option -s or default stage('dev')
  region: ap-northeast-2
  environment:
    NODE_ENV: ${self:custom.environment.NODE_ENV}


functions:
  app:
    handler: ./src/lambda.handler
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: '/api/v1/{proxy+}'
          method: any
          cors: true

